theme: jekyll-theme-slate
title: Honoka's Room
description:  ୨୧････････････････････････････････････････････････････････････୨୧
plugins:
  - jemoji
url: "https://honokahayashi.github.io"
markdown: kramdown
