theme: jekyll-theme-slate
title: The homepage of Honoka Hayashi, flower & sweets
description: What you will find here are flower pictures and sweets recipes.
plugins:
  - jemoji
url: "https://michaelschiltz.github.io/&quot;
markdown: kramdown
