theme: jekyll-theme-slate
title: Welcome to my homepage:)
description: What you will find here is my research project and my hobbies.  
→ Under construction. Coming soon!
plugins:
  - jemoji
url: "https://honokahayashi.github.io"
markdown: kramdown
